lvim.keys.normal_mode["<F2>"] = "<Cmd>lua require('jdtls').extract_variable()<CR>"
lvim.keys.normal_mode["<F3>"] = "<Cmd>lua require('jdtls').extract_constant()<CR>"
lvim.keys.normal_mode["<F4>"] = "<Cmd>lua require'jdtls'.organize_imports()<CR>"
lvim.keys.normal_mode["<F5>"] = ":terminal mvn eclipse:eclipse<CR>"
lvim.keys.normal_mode["<F9>"] = "<Cmd>lua require'jdtls'.test_nearest_method()<CR>"
lvim.keys.normal_mode["<F7>"] = "<cmd>lua require'dapui'.toggle({reset = true})<cr>"
lvim.keys.normal_mode["<F10>"] = ":terminal mvn spring-boot:run<CR>"
